version: '3.8'
services:
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - currency-rate
    networks:
      - app-network

  currency-rate:
    build: ./
    command:
      - ./app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_POSTGRES_USER=postgres
      - DB_POSTGRES_PASSWORD=qwerty
    entrypoint: ./wait-for-postgres.sh db:5432
    networks:
      - app-network

  db:
    image: postgres:16.2-alpine
    restart: always
    ports:
      - '5444:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=plata
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge